# Workflow to trigger regression tests regFile.py whenever a new commit made

name: swaggertests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
       - swaggertest
  pull_request:
    branches: 
       - swaggertest

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          inputs:
                  branch:
                          description: 'Branch to checkout'
                          requried: true
                          default: 'swaggertest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-python-script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
                ref: 'swaggertest'

      - name: Set up python
        uses: actions/setup-python@v4
        with:
                python-version: '3.x'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs deugging
      - name: Run debugging commands
        run: ls -ltr

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Custom tasks
      - name: Run regression tests
        run: |
          python regFile.py
